---
- hosts: localhost

  tasks:
  - name: Enable cobbler module
    ansible.builtin.command: dnf module enable -y cobbler
    args:
      warn: false

  - name: Install cobbler and related packages
    ansible.builtin.package:
      name:
      - cobbler
      - cobbler-web
      - pykickstart
      - httpd
      - rsync-daemon
      - dhcp-server
      - tftp-server
      state: present

  - name: Start cobbler and related services
    ansible.builtin.systemd:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - httpd
      - rsyncd
      - cobblerd
      - tftp

  - name: Copy config files
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
      mode: "{{ item.mode }}"
    with_items:
      - { src: 'etc/cobbler/settings', dest: '/etc/cobbler/settings', owner: 'root', group: 'root', mode: '0644' }
      - { src: 'etc/cobbler/dhcp.template', dest: '/etc/cobbler/dhcp.template', owner: 'root', group: 'root', mode: '0644' }
      - { src: 'etc/cobbler/rsync.template', dest: '/etc/cobbler/rsync.template', owner: 'root', group: 'root', mode: '0644' }
      - { src: 'etc/cobbler/templates/rhel79.ks', dest: '/var/lib/cobbler/templates/rhel79.ks', owner: 'root', group: 'root', mode: '0644' }
    notify:
      - Restart cobbler services
      - Sync cobbler
      - Start dhcpd

  - name: Force all notified handlers to run at this point, not waiting for normal sync points
    meta: flush_handlers

  - name: Get cobbler loaders
    ansible.builtin.command: /usr/bin/cobbler get-loaders

  - name: Generate cobbler boot files
    ansible.builtin.command: /usr/share/cobbler/bin/mkgrub.sh

  - name: Copy grub boot loader
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
      mode: "{{ item.mode }}"
    with_items:
      - { src: 'var/lib/tftpboot/grubx64.efi', dest: '/var/lib/tftpboot/grubx64.efi', owner: 'root', group: 'root', mode: '0644' }
      - { src: 'var/lib/tftpboot/grubx64.efi', dest: '/var/lib/tftpboot/grub/grubx64.efi', owner: 'root', group: 'root', mode: '0644' }

  handlers:
    - name: Restart cobbler services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items:
        - cobblerd
        - httpd
        - rsyncd
        - tftp

    - name: Sync cobbler
      ansible.builtin.command: /usr/bin/cobbler sync

    - name: Restart cobblerd
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items:
        - cobblerd

    - name: Start dhcpd 
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - dhcpd
